### ISSUE TITLE
marionette subrouter is causing double routing

### ISSUE THREAD

**Issue by newtonianb** [pushchris/backbone.marionette.subrouter#8] opened 2015-02-26 04:40 UTC
I might be misunderstanding something but all I can do right now is compare previous behavior (without marionette subrouter) and current behavior (with marionette subrouter). What I noticed is when using Marionette Subrouter then my controller function is being hit twice...

I attached below the full details
![present_3](https://cloud.githubusercontent.com/assets/2313644/6386503/9075613a-bd47-11e4-86ac-22c19e0fb3d4.png)

![present_1](https://cloud.githubusercontent.com/assets/2313644/6386504/94b36468-bd47-11e4-9574-977afe1d8237.jpg)

![present_2](https://cloud.githubusercontent.com/assets/2313644/6386505/96a8b886-bd47-11e4-8af8-4a132e7b7019.jpg)

![present_4](https://cloud.githubusercontent.com/assets/2313644/6386526/e9ab370c-bd47-11e4-9822-a081f4d136b8.jpg)

**Comment by newtonianb** [comment] 2015-03-05 17:15
I think it was because one of my subroute had a similar name as root path route, i'll investigate more.

**Comment by jperasmus** [comment] 2015-07-07 15:38
Hi @newtonianb did you ever figure out something more about this and whether it was actually because of similar names with the root path route? I'm experiencing something similar where the route methods are being called twice.

**Comment by newtonianb** [comment] 2015-07-07 16:04
Sorry no, we ended up writing our custom subrouter so I don't know for sure at this point.

**Comment by jperasmus** [comment] 2015-07-07 16:07
Okay, thanks for getting back so quickly. Will have to dig a bit deeper myself then.

**Comment by pushchris** [comment] 2015-07-07 16:17
@jperasmus Let me know if you find anything and I'll merge it in. Else I may have some time to look into it this week.

**Comment by pushchris** [comment] 2015-07-07 19:13
@jperasmus Can you explain the issue a little bit more? Is this happening on navigation or on page load?

**Comment by jperasmus** [comment] 2015-07-07 19:37
@pushchris Hi Chris, I'm trying to look into this as well, but no luck yet. The issue is happening on page load and it also again calls the router method when navigating away. Not sure if that is related to the problem.

Is there anything else specific you would want to know about the issue that I can provide?

**Comment by pushchris** [comment] 2015-07-07 19:43
Is there anything more you can tell me about how it's set up? Just off the top of my head: the page load issue may be related to when you call Backbone.history.start(), not sure about the navigation one. Duplicate calls to me sounds like the router got invoked multiple times somehow

**Comment by jperasmus** [comment] 2015-07-07 20:15
Thanks for this comment, it led me to the issue. The problem is not in this plugin, but in our code. There is a call to Backbone.history.loadUrl(Backbone.history.fragment); after the Backbone.history.start(); has been called, which explains why the router method gets called twice on page load. Not sure the reason for this piece of code, because it is a project we've inherited, so I'll have to try and find out if there is a particular reason this was included.

Thanks for all your help. I would say it's safe to close this bug.

**Closed** 2015-07-07 20:17 UTC
